services:
  backend:
    build:
      context: ./backend
    container_name: sql_runner_backend
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: production
      PORT: 8000
      DEBUG: "False"
      DATABASE_URL: app/sql_runner.db
    volumes:
      - ./backend:/app
    command: >
      sh -c "python app/app.py"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE: "http://127.0.0.1:8000/api"
    container_name: sql_runner_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
